### ISSUE TITLE
Comparisions with similar tasks

### ISSUE THREAD

**Issue by ghost** [cnyvfang/P2LDGAN#1]
https://github.com/Mukosame/Anime2Sketch
https://github.com/lllyasviel/sketchKeras
https://github.com/ljsabc/MangaLineExtraction_PyTorch

**Comment by cnyvfang** [comment]
Thank you for your suggestions! Actually, our work can be used in translating anime pictures into line drawings but the main purpose is for translating real persons' full-body photos into line drawings. 

We will make comparisons with those projects in recent when we have time! 

Thanks again!
